services:
  efcorelearn:
    container_name: efcorelearn
    environment:    
      - ASPNETCORE_ENVIRONMENT=Development 
    ports:
      - "5000:8080" 
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresdb
    environment:
      - POSTGRES_USER=ADMIN    
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data/ 